---
# tasks file for docker-registry
# docker push smaii/angular-ci:tagname
# tasks file for docker
- name: push image to docker hub
  docker_image:
    name: "angular-ci:v1"
    repository: "smaii/angular-ci:v1"
    push: yes
