---
# tasks file for docker-registry
- name: Log into DockerHub
  docker_login:
    username: smaii
    password: Maja00001

- name: Tag and push to docker hub
  docker_image:
    name: angular:latest
    repository: smaii/angular-ci
    tag: end
    push: yes